name: CREATE_STACK

on: 
  workflow_dispatch:
    inputs:
      stack-name:
        description: 'Enter new stack name here.'
        required: true
        default: ''

jobs:
  create-stack:
    name: Create MyTradables CDK Stack.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Add Registery Token
        run: |
          echo "@mytradables:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{secrets.MT_GITHUB_TOKEN}}" >> $HOME/.npmrc

      - name: Install Dependencies.
        run: npm ci

      - name: Create Stack.
        run: npx ts-node ./setup/index.ts -n ${{ github.event.inputs.stack-name }}
        env:
          MT_GITHUB_TOKEN: ${{ secrets.MT_GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
